<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1 </p>

Students name in this Group:

In [3]:
# importing numpy
import numpy as np

In [4]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
arr = np.array([1,2,3,5,0])
print(arr)

non_zero = arr.all()


if non_zero == False:
    print("Elements contain zero element.")
else:
    print("All of the elements are non-zero.")

check=np.nonzero(arr)
print(arr[check])



[1 2 3 5 0]
Elements contain zero element.
[1 2 3 5]


In [13]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
arr2 = np.array([3,-1,3,7,2])
print(arr2)

non_zero = arr2.any()


if non_zero == False:
    print("Elements contain zero element.")
else:
    print("At least one of the elements is non-zero.")


[ 3 -1  3  7  2]
At least one of the elements is non-zero.


In [14]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
arr3 = np.array([0, 0, 0, 0])
print(arr3)
non_zero = arr3.any()


if non_zero == False:
    print("Elements contain zero element.")
else:
    print("At least one of the elements is non-zero.")

check3 = np.nonzero(arr3)
print(arr3[check3])

[0 0 0 0]
Elements contain zero element.
[]


In [7]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
arr4 = np.array([56, -2, 7])
print(arr4)
print("the item size:", arr4.itemsize)
print("size of array:",arr4.size)
print("The amount of memory required to store is",arr4.itemsize*arr4.size,"bits.")

[56 -2  7]
the item size: 8
size of array: 3
The amount of memory required to store is 24 bits.


In [8]:
# Create a numpy array with 10 zeros and print the array.
zero = np.zeros(10)
print(zero)
# Create a numpy array with 6 ones and print the array.
one = np.ones(6)
print(one)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
three =3* np.ones((12),dtype=int)
print(three)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [9]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr5 = np.arange(8,21)
print(arr5)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr6 = np.arange(8,21,2)
print(arr6)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [12]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
randarray = np.random.normal(2, 0.5, 100)
print("The mean in the array is: ", randarray.mean())
print("The max element in the array is: ", randarray.max())
print("The min element in the array is: ", randarray.min())
print("The std in the array is: ", randarray.std())
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
randarray2 = np.random.normal(2, 0.5, 1000)
print("The mean in the array is: ", randarray2.mean())
print("The max element in the array is: ", randarray2.max())
print("The min element in the array is: ", randarray2.min())
print("The std in the array is: ", randarray2.std())
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
randarray3 = np.random.normal(2, 0.5, 1000000)
print("The mean in the array is: ", randarray3.mean())
print("The max element in the array is: ", randarray3.max())
print("The min element in the array is: ", randarray3.min())
print("The std in the array is: ", randarray3.std())


The mean in the array is:  2.0559186124931976
The max element in the array is:  3.445047974774611
The min element in the array is:  1.0942328395389842
The std in the array is:  0.4898102591742426
The mean in the array is:  1.988130177119299
The max element in the array is:  3.359459223135341
The min element in the array is:  0.35186639025417144
The std in the array is:  0.481265384048017
The mean in the array is:  1.9999940092084492
The max element in the array is:  4.4653110507202385
The min element in the array is:  -0.4471912972312664
The std in the array is:  0.5000251625398875


# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
 The mean and std will be closer to the amount we set which are 2 and 0.5

Yes, as the randomly generated values increases in quantity(data):
1) the mean gets closer to 2 (supplied or theoretical mean)
2) The std deviation also gets closer to 0.5 (supplied or theoretical std)