<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [2]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det


In [3]:
a = np.array([[5,2,3],[6,1,3],[2,4,1]])
print(a)

[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [16]:
b = a[0:2,0:2]
print(b)

[[5 2]
 [6 1]]


In [18]:
c = a[1:3,1:3]
print(c)

[[1 3]
 [4 1]]
